
package WebServiceDemoClient.webservicedemoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://WebServiceDemoService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SayHello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SayHello", targetNamespace = "http://WebServiceDemoService/", className = "webservicedemoservice.SayHello")
    @ResponseWrapper(localName = "SayHelloResponse", targetNamespace = "http://WebServiceDemoService/", className = "webservicedemoservice.SayHelloResponse")
    @Action(input = "http://WebServiceDemoService/HelloService/SayHelloRequest", output = "http://WebServiceDemoService/HelloService/SayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
